apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |-
    [options]
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = odoo
    data_dir = /var/lib/odoo
    admin_passwd = admin
    addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

    server_wide_modules = web

    ; Google Cloud Storage (S3-compatible) config
    fs_attachment_s3_endpoint_url = https://storage.googleapis.com
    fs_attachment_s3_bucket = test-odoo-bucket
    fs_attachment_s3_region = us
    fs_attachment_s3_use_ssl = true