apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |-
    [options]
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = odoo
    data_dir = /var/lib/odoo
    admin_passwd = admin

    server_wide_modules = web

    ; RustFS (S3-compatible) config
    fs_attachment_s3_endpoint_url = http://rustfs.rustfs.svc.cluster.local:9000
    fs_attachment_s3_bucket = odoo-filestore
    fs_attachment_s3_region = us-east-1
    fs_attachment_s3_use_ssl = false