apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: odoo
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "OM0glFPNXQI49nyfLk3D"
  AWS_SECRET_ACCESS_KEY: "uK0mgESziV6P7C259x8IrpF1WURfnNXcHy4BYdQe" #En estos necesito hacerlo de otra manera en el futuro, no sirve solo que quede en base64 (usar algun proveedor de secrets)
  AWS_DEFAULT_REGION: "us-east-1"
