apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: odoo-app
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - odoo-app.test.local
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: default-odoo-app-8069
              namespace: gloo-system
